# Generated by Django 3.2 on 2021-08-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloudStack_Instance_info',
            fields=[
                ('ins_id', models.TextField(primary_key=True, serialize=False)),
                ('user_id', models.TextField()),
                ('ins_name', models.TextField()),
                ('vol_id', models.TextField()),
                ('os_name', models.TextField()),
                ('created', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CloudStack_Snapshot_info',
            fields=[
                ('snap_id', models.TextField(primary_key=True, serialize=False)),
                ('user_id', models.TextField()),
                ('snap_name', models.TextField()),
                ('os_name', models.TextField()),
                ('created', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OpenStack_Instance_info',
            fields=[
                ('ins_id', models.TextField(primary_key=True, serialize=False)),
                ('user_id', models.TextField()),
                ('ins_name', models.TextField()),
                ('vol_id', models.TextField()),
                ('os_name', models.TextField()),
                ('created', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OpenStack_Snapshot_info',
            fields=[
                ('snap_id', models.TextField(primary_key=True, serialize=False)),
                ('user_id', models.TextField()),
                ('snap_name', models.TextField()),
                ('os_name', models.TextField()),
                ('created', models.TextField()),
            ],
        ),
    ]
